name: Poetry
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install poetry==1.1.12
      - run: poetry install
      - run: poetry run pytest tests
