
name: Unit tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8.8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .
      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/